/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidex_JNI_test */

#ifndef _Included_com_example_androidex_JNI_test
#define _Included_com_example_androidex_JNI_test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_androidex_JNI_test
 * Method:    sendToBoard
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_example_androidex_JNI_1test_sendToBoard
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_example_androidex_JNI_test
 * Method:    rcvThread
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_androidex_JNI_1test_rcvThread
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
